apiVersion: v2
name: bunnycdn-exporter
version: 1.2.6
appVersion: 0.2.4
description: Prometheus exporter for BunnyCDN
home: https://bunny.net/
sources:
  - https://github.com/ricardo-ch/bunnycdn_exporter
  - https://github.com/ricardo-ch/helm-charts/tree/main/charts/bunnycdn-exporter
maintainers:
  - name: ricardo-ch
    email: sre@ricardo.ch
keywords:
  - bunnycdn
annotations:
  artifacthub.io/changes: |
    - Readme template change
  artifacthub.io/images: |
    - name: bunnycdn_exporter
      image: ricardoag/bunnycdn_exporter:v0.2.3
