apiVersion: v2
name: PromLens
version: 0.2.0
description: This Chart installs and configures PromLens
sources: ["https://github.com/ricardo-ch/helm-charts/tree/main/charts/promlens"]
maintainers:
  - name: ricardo-ch
    email: sre@ricardo.ch
