apiVersion: v2
name: promlens
version: 1.0.6
appVersion: 0.11.0
description: This Chart installs and configures PromLens from PromLabs.
home: https://promlens.com
icon: https://promlens.com/favicon-32x32.png
sources:
  - https://github.com/ricardo-ch/helm-charts/tree/main/charts/promlens
  - https://github.com/promlabs/promlens-public
maintainers:
  - name: ricardo-ch
    email: sre@ricardo.ch
keywords:
  - promlens
  - promlabs
  - prometheus
  - promql
annotations:
  artifacthub.io/changes: |
    - Add options for link sharing via mysql database
  artifacthub.io/images: |
    - name: promlens
      image: promlabs/promlens:v0.11.0
