apiVersion: v2
name: kafka-proxy
version: 0.2.11
appVersion: 0.3.6
description: Deploying the grepplabs kafka-proxy as a StatefulSet with a GKE LoadBalancer
home: https://github.com/grepplabs/kafka-proxy
sources:
  - https://github.com/grepplabs/kafka-proxy
  - https://github.com/ricardo-ch/helm-charts/tree/main/charts/kafka-proxy
maintainers:
  - name: ricardo-ch
    email: sre@ricardo.ch
keywords:
  - kafka-proxy
annotations:
  artifacthub.io/changes: |
    - "fix readme title"
  artifacthub.io/images: |
    - name: kafka-proxy
      image: grepplabs/kafka-proxy:0.3.6
